services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cargonauta-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./discord_bot.py:/app/discord_bot.py:ro
    environment:
      - TZ=America/Sao_Paulo
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - ID_DO_CARGO_BATE_PAPO=${ID_DO_CARGO_BATE_PAPO}
      - ID_DO_CARGO_CINE_AMONG=${ID_DO_CARGO_CINE_AMONG}
      - ID_DO_CARGO_TACA_AMONG=${ID_DO_CARGO_TACA_AMONG}
      - ID_DO_CARGO_HOME_OFFICE=${ID_DO_CARGO_HOME_OFFICE}
      - ID_DO_CARGO_PROGRAMACAO_COMPETITIVA=${ID_DO_CARGO_PROGRAMACAO_COMPETITIVA}
      - WELCOME_MESSAGE_ID=${WELCOME_MESSAGE_ID}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
